### ISSUE TITLE
Split SVN monorepo

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/TWiStErRob-env#8]
For how, see https://github.com/TWiStErRob/TWiStErRob-env/tree/master/svn2git-migration

 - [ ] Documents\ -> empty, never had contents, delete
 - [ ] Examples\
 - [ ] Hacks\
 - [ ] Interviews\
 - [ ] Libraries\android_google-play-services_lib\
 - [ ] Libraries\android_google-play-services_lib_froyo\
 - [ ] Libraries\android_support-v7_appcompat\
 - [ ] Libraries\TWiStEr.Annotations\
 - [ ] Libraries\TWiStEr.BitTorrent\
 - [ ] Libraries\TWiStEr.Controls.WPF\
 - [ ] Libraries\TWiStEr.Converters\
 - [ ] Libraries\TWiStEr.DataStructures\
 - [ ] Libraries\TWiStEr.Extensions\
 - [ ] Libraries\TWiStEr.FormalLanguages\
 - [ ] Libraries\TWiStEr.Fuzzy\
 - [ ] Libraries\TWiStEr.NeuralNetworks\
 - [ ] Libraries\twister-lib-android\
 - [ ] Libraries\twister-lib-java\
 - [x] Libraries\twister-plugin-gradle\ -> https://github.com/TWiStErRob/net.twisterrob.gradle/issues/95
 - [ ] Projects\Android Color Filters\ -> https://github.com/TWiStErRob/net.twisterrob.colorfilters/issues/16
 - [ ] Projects\Better London Travel\ -> https://github.com/TWiStErRob/net.twisterrob.travel/issues/2
 - [ ] Projects\Cashier\
 - [x] Projects\Cinema\ -> [**Publish & Maintenance 2021**](https://github.com/TWiStErRob/net.twisterrob.cinema/milestone/1) net.twisterrob.cinema/M1
 - [ ] Projects\Color Schema Manager\
 - [ ] Projects\Extra Refactorings\
 - [ ] Projects\Family Tree\
 - [ ] Projects\Git History Builder\
 - [ ] Projects\GPS Track Analyzer\
 - [ ] Projects\Inventory\ -> https://github.com/TWiStErRob/net.twisterrob.inventory/issues/171
       challenge: twister-lib-android & twister-lib-java
 - [ ] Projects\Language Cross Reference\
 - [ ] Projects\ListMatcher\
 - [ ] Projects\Minesweeper Multiplayer\
 - [ ] Projects\Mosaic\
 - [ ] Projects\Office Translator\
 - [ ] Projects\Path Finder\
 - [ ] Projects\PRSysMon2\
 - [ ] Projects\Quick Public Transport\
 - [ ] Projects\Regex Testbed\
 - [ ] Projects\Sensor3D\
 - [x] Projects\Sun\ -> https://github.com/TWiStErRob/net.twisterrob.sun/issues/5
 - [ ] Projects\Syntax Highlight Editor\
 - [ ] Projects\WebTwister\
 - [ ] School\
 - [ ] Utilities\Calendar Filler\
 - [ ] Utilities\Console Highlighter\
 - [ ] Utilities\Direct File Transfer\
 - [ ] Utilities\Graph Energy\
 - [ ] Utilities\GridMaker\
 - [ ] Utilities\Paint.NET\
 - [ ] Utilities\Pre-Commit Hook\
 - [ ] Utilities\Processing\
 - [ ] Utilities\Regex Color Editor\
 - [ ] Utilities\Series Manager\
 - [ ] Utilities\Simple Utilities\
 - [ ] Utilities\Solvers\
 - [ ] Utilities\SpecialGraph\
 - [ ] Utilities\StereoViewer\
 - [ ] Utilities\TimeShifter\
 - [ ] Utilities\ViewModelGenerator\
 - [ ] Utilities\WhatsUp\
 - [ ] Utilities\XMLReorder\
 - [ ] Web\Amoeba\
 - [ ] Web\auroville.hu\
 - [ ] Web\Browser Scripts\
 - [ ] Web\Google Calendar Printer\
 - [ ] Web\Google Maps Icons\
 - [ ] Web\Portable Apache Server\
 - [ ] Web\QuickJSONFormatterLib\
 - [ ] Web\ScreenJunkies Plus\
 - [x] Web\Test -> https://github.com/TWiStErRob/net.twisterrob.healthcheck/commit/02b48c69ae30bbed9cfae33cffbec1c5fde30957
 - [ ] Web\twisterrob.net\
 - [ ] Web\VotingTwister\
 - [ ] Web\www.twisterrob.net\ -> https://github.com/TWiStErRob/twisterrob.github.io  
       Need to figure out how to store private files.
